Remove Sytem.Runtime dlls
-This dll causes Error CS1703: Multiple assemblies with equivalent identity have been imported when switching from VS2013 to VS2015